apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "p3ifs3LY4Bq1SseMu8n+IOlx5jiS4ExwywV6TTSF2H01kU3pZvFR5tVmrieXcH0J\nttVUbQ32tpp5/WnwZVznXsHSxI+smtSXxHVEU7k2bLgGxknotQhg0S/ILvktF6Ab\nBg83+rqDQ4tQC9LPGDonzFU8ItEjTUfsDUfiTguzgmw="
